[build]
  publish = "."

# Disable Pretty URLs automatic trailing slash behavior
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Canonical-Tag = "enabled"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
